# Generated by Django 4.0.4 on 2022-07-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
