# Generated by Django 4.0.4 on 2022-07-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
